# Generated by Django 5.2.12 on 2026-03-12 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_donhang_da_hoan_tien_alter_donhang_phuong_thuc_tt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='da_thanh_toan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ma_thanh_toan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='donhang',
            name='thanh_toan_luc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='phuong_thuc_tt',
            field=models.CharField(choices=[('COD', 'COD (Thanh toán khi nhận hàng)'), ('ChuyenKhoan', 'Chuyển khoản ngân hàng'), ('ViDienTu', 'Ví điện tử')], default='COD', max_length=50),
        ),
        migrations.CreateModel(
            name='WalletTopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('transfer_note', models.CharField(blank=True, default='', max_length=64)),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã nhận callback'), ('approved', 'Đã cộng ví'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_topups', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to='shop.wallet')),
            ],
        ),
    ]
