# Generated by Django 5.2.12 on 2026-03-13 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_donhang_da_thanh_toan_donhang_ma_thanh_toan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(choices=[('childhood_name', 'Tên người bạn thân thời thơ ấu của bạn là gì?'), ('first_school', 'Tên trường tiểu học đầu tiên của bạn là gì?'), ('favorite_teacher', 'Tên giáo viên bạn nhớ nhất là gì?'), ('first_pet', 'Tên thú cưng đầu tiên của bạn là gì?'), ('birth_city', 'Bạn sinh ra ở thành phố nào?'), ('favorite_book', 'Tên cuốn sách yêu thích thời nhỏ của bạn là gì?')], max_length=50)),
                ('answer_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(choices=[('childhood_name', 'Tên người bạn thân thời thơ ấu của bạn là gì?'), ('first_school', 'Tên trường tiểu học đầu tiên của bạn là gì?'), ('favorite_teacher', 'Tên giáo viên bạn nhớ nhất là gì?'), ('first_pet', 'Tên thú cưng đầu tiên của bạn là gì?'), ('birth_city', 'Bạn sinh ra ở thành phố nào?'), ('favorite_book', 'Tên cuốn sách yêu thích thời nhỏ của bạn là gì?')], max_length=50)),
                ('answer_2', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
