# Generated by Django 5.2.12 on 2026-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_voucher_donhang_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='gia_khuyen_mai',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
