# Generated by Django 5.2.12 on 2026-04-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sanpham_gia_khuyen_mai'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='flash_sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='flash_sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
