# Generated by Django 5.2.12 on 2026-04-02 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_sanpham_ton_kho_orderstatushistory_savedaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_stock', models.IntegerField(default=0)),
                ('quantity_change', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('change_type', models.CharField(choices=[('manual_set', 'Admin đặt lại tồn kho'), ('manual_in', 'Admin nhập kho'), ('manual_out', 'Admin xuất kho'), ('order_out', 'Trừ kho theo đơn hàng'), ('order_return', 'Hoàn kho do huỷ / từ chối đơn')], default='manual_set', max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_histories', to='shop.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_histories', to='shop.sanpham')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
