# Generated by Django 5.2.12 on 2026-04-02 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_inventoryhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('sdt', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('dia_chi', models.CharField(blank=True, default='', max_length=255)),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ten', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='change_type',
            field=models.CharField(choices=[('manual_set', 'Admin đặt lại tồn kho'), ('manual_in', 'Admin nhập kho'), ('manual_out', 'Admin xuất kho'), ('receipt_in', 'Nhập kho theo phiếu nhập'), ('order_out', 'Trừ kho theo đơn hàng'), ('order_return', 'Hoàn kho do huỷ / từ chối đơn')], default='manual_set', max_length=30),
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('received', 'Đã nhập kho'), ('cancelled', 'Đã huỷ')], default='draft', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to='shop.nhacungcap')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhieuNhapKhoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('don_gia_nhap', models.IntegerField(default=0)),
                ('batch_code', models.CharField(blank=True, default='', max_length=50)),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=255)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.phieunhapkho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_items', to='shop.sanpham')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50)),
                ('so_luong_nhap', models.IntegerField(default=0)),
                ('so_luong_con_lai', models.IntegerField(default=0)),
                ('don_gia_nhap', models.IntegerField(default=0)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_batches', to=settings.AUTH_USER_MODEL)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='shop.sanpham')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batches', to='shop.nhacungcap')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.phieunhapkho')),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.phieunhapkhoitem')),
            ],
            options={
                'ordering': ['-imported_at', '-id'],
            },
        ),
    ]
