# Generated by ChatGPT

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_sanpham_search_tags_productimage_productreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReviewImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="reviews/")),
                ("caption", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("review", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="shop.productreview")),
            ],
            options={"ordering": ["id"]},
        ),
    ]
