# Generated by Django 5.2.13 on 2026-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productreviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Confirmed', 'Đã xác nhận'), ('Shipping', 'Đang giao'), ('Completed', 'Hoàn thành'), ('Cancelled', 'Đã hủy'), ('Rejected', 'Từ chối')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='phieunhapkho',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('received', 'Đã nhập kho'), ('cancelled', 'Đã hủy')], default='draft', max_length=20),
        ),
    ]
